### ISSUE TITLE
There should be a way to store data from GitHub

### ISSUE THREAD

**Issue by auernige** [snek-at/front#15]
**Is your feature request related to a problem? Please describe.**
There should be a way to store data received from GitHub API

**Describe the solution you'd like**
The JSON data from the API should be translated and stored into a database
**Additional context**
Ref: https://github.com/agershun/alasql

**Comment by kleberbaum** [comment]
This issue has been reopened due to issue #42.

**Comment by kleberbaum** [comment]
This issue has been resolved with pull request #44.
