### ISSUE TITLE
There should be a way to get data from GitHub

### ISSUE THREAD

**Issue by auernige** [snek-at/front#16]
Is your feature request related to a problem? Please describe.
There should be a way to get user and calendar data from GitHub.

Describe the solution you'd like
Implement steps to fetch the GitHub data via GitHub's GQL API.

Suggested folder structure:
src/intel/implement/UtilsGithub/?

GitHubUtils need a method that requires a user object as a parameter and returns all information from GitHub as one object.

The authorization token is set as a variable in .env for now. In later septs, it will be replaced with a cookie.

Additional context
The foundation can be found at:
https://github.com/snek-at/concept/blob/master/src/utils/GitHubUtils/index.js
https://github.com/snek-at/concept/blob/master/src/handler/GitHub/index.js
.env -> https://github.com/snek-at/concept/blob/master/README.md

**Comment by kleberbaum** [comment]
This issue has been reopened due to issue #42.

**Comment by kleberbaum** [comment]
This issue has been resolved with pull request #44.
