### ISSUE TITLE
Github data processing fails

### ISSUE THREAD

**Issue by auernige** [snek-at/front#23]
**Describe the bug**
The Translator in the GitHubUtils fails to handle the data from GitHub

**To Reproduce**
1. Call the fill function in UtilsGithub

**Expected behavior**
The data should be filled in the Database

**Desktop (please complete the following information):**
  - OS: Win 10
  - Browser: chrome
  - Version: 78.0.3904.97

**Additional context**
The reason for the bug is known and fixed as soon as possible

**Comment by kleberbaum** [comment]
This issue has been reopened due to issue #42.

**Comment by kleberbaum** [comment]
This issue has been resolved with pull request #50.
