### ISSUE TITLE
There should be a way to request OAuth access token from GitHub

### ISSUE THREAD

**Issue by pinterid** [snek-at/front#33]
**Is your feature request related to a problem? Please describe.**
SNEK is currently using an open access token to get data from GitHub.

**Describe the solution you'd like**
SNEK should use OAuth to get an access token from GitHub.

**Additional context**
References:
- https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/
- https://medium.com/@mattmazzola/react-simple-auth-react-redux-oauth-2-0-de6ea9df0a63
- https://github.com/mattmazzola/react-simple-auth

**Comment by kleberbaum** [comment]
This issue has been reopened due to issue #42.
