### ISSUE TITLE
Add a register component in landing page

### ISSUE THREAD

**Issue by Aichnerc** [snek-at/front#35]
**Is your feature request related to a problem? Please describe.**
Currently, there is neigter a Landing page component nor a register component.

**Describe the solution you'd like**
A register component should be added to a Landing page component. It should contain basic local functionality and be ready to get implemented to oAuth.

**Comment by Aichnerc** [comment]
This issue has been resolved with pull request #36

**Comment by kleberbaum** [comment]
This issue has been reopened due to issue #42.

**Comment by kleberbaum** [comment]
This issue has been resolved with pull request #58.
