### ISSUE TITLE
Contribs table gets duplicate data

### ISSUE THREAD

**Issue by auernige** [snek-at/front#41]
**Describe the bug**
The contribs table gets duplicate entries. For every day in a year, all existing contribs get stored in the table.

**To Reproduce**
1. Call fillCalendar function

**Expected behavior**
Every contribution should only be stored once

**Desktop (please complete the following information):**
  - OS: Windows 10
  - Browser: chrome
  - Version: 78.0.3904.97

**Comment by kleberbaum** [comment]
This issue has been resolved with pull request #59.
