### ISSUE TITLE
The README is still a bit generic

### ISSUE THREAD

**Issue by kleberbaum** [snek-at/front#5]
**Describe the feature or change you'd like**
I would like to rework the README so it serves it's purpose.

**Additional context**
Ref: https://help.github.com/en/articles/about-readmes
Ref: https://github.com/snek-at/front-old/blob/master/README.md

**Comment by Aichnerc** [comment]
This issue has been resolved with pull request #7

**Comment by kleberbaum** [comment]
This issue has been resolved with pull request. #7
